name: Java CII

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin' # Use 'temurin' or your preferred distribution
    - name: Build with Maven
      run: mvn -B package --file HelloCICDIMAGE/pom.xml
    - name: Build with Maven
      run: mvn clean install
    - name: Run test
      run: mvn clean package
